---
duply_backup_profiles:
  nexus:
    # WARNING: Changing any of these profile settings could make duply unable to interact with existing backups
    # that were created with different settings.
    conf:
      target: s3+http://{{ unidata_backups_bucket }}/nexus-iac/{{ ansible_hostname }}
      source: /

      max_age: 6M          # Delete backups when they are more than six months old.
      max_fullbkp_age: 2M  # Do a full backup (instead of incremental) if the last full was done more than 2 months ago.

      # Additional duplicity command line options. Don't forget to leave a separating space char at the end.
      #
      # This parameter will ignore the following error:
      #     Fatal Error: Backup source host has changed.
      #     Current hostname: nexus-prod.jetstreamlocal
      #     Previous hostname: localhost
      #     Aborting because you may have accidentally tried to backup two different data sets to the same remote
      #     location, or using the same archive directory. If this is not a mistake, use the --allow-source-mismatch
      #     switch to avoid seeing this message.
      #
      # I've also seen instances where "Current hostname: localhost" and "Previous hostname: nexus-prod.jetstreamlocal".
      # Given that Current and Previous are swapping back and forth, seemingly at random, we've got to enable this
      # option, even though it's slightly risky.
      dupl_params: '--allow-source-mismatch '

      # Although we could encrypt the archive, we've decided not to bother because our data is being stored in a
      # private S3 bucket. Moreover, none of the data is sensitive anyway.

    excludes:  # Misleading key name; we can also specify includes.
      # Items beginning with a '+' are included. Items beginning with a '-' are excluded.
      # Paths are relative to 'source' (i.e. the root directory).
      - '+ {{ nexus_backup_dir }}'
      - '+ {{ nexus_data_dir }}/blobs'
      - '+ {{ apache_log_dir }}'
      - '- **'          # Exclude every other path that we haven't specifically included above.
