---
- name: Get status of permanent Vault password file.
  stat: path={{ permanent_vault_password_file }}
  register: perm_file_stat

- block:
  - name: Create parent directory of permanent Vault password file.
    file:
      path: "{{ permanent_vault_password_file | dirname }}"
      state: directory  # Will create all immediate subdirectories as well.
      owner: "{{ nexus_os_user }}"
      group: "{{ nexus_os_group }}"

  - name: Get status of temporary Vault password file.
    stat: path={{ temporary_vault_password_file }}
    register: temp_file_stat

  - block:
    - name: Copy temporary Vault password file to permanent location, changing ownership and attributes.
      copy:
        src: "{{ temporary_vault_password_file }}"
        dest: "{{ permanent_vault_password_file }}"
        owner: "{{ nexus_os_user }}"
        group: "{{ nexus_os_group }}"
        mode: 0400  # Readable only by 'nexus_os_user'.
        remote_src: true

    # Ansible does not have a 'move' module; we must copy then delete. See https://stackoverflow.com/questions/24162996
    - name: Delete temporary Vault password file.
      file:
        path: "{{ temporary_vault_password_file }}"
        state: absent
    # A temporary Vault password file exists. This file was put in place outside of Ansible, by either Vagrant or
    # Packer. We'll use it in preference to the vault-password script that's included in this role.
    when: temp_file_stat.stat.exists

  - name: Copy default Vault password script to permanent location, changing ownership and attributes.
    copy:
      src: vault-password
      dest: "{{ permanent_vault_password_file }}"
      owner: "{{ nexus_os_user }}"
      group: "{{ nexus_os_group }}"
      mode: 0500  # Readable and executable only by 'nexus_os_user'.
    # No temporary Vault password file exists. Therefore, we'll copy over the default vault-password script to the
    # permanent location. The script is used in Docker and simply prints the value of the VAULT_PASSWORD env variable.
    # Obviously, that variable will have to be set beforehand by some means, e.g. the Travis admin console.
    when: not temp_file_stat.stat.exists
  when: not perm_file_stat.stat.exists   # Nothing has been copied to the permanent Vault password file location yet.
