# Empty for now, but this will be where we override default values of the variables defined in variables.tf.
# We'll probably override the "image" variable with info for Packer-built images.
# This file may be generated by a script, not edited by hand.
