---
  # Edit /etc/hosts so that we can resolve these hostnames in our tests. In production, DNS will do the mapping.
- name: Map '{{ artifacts_hostname }}' to '{{ application_host }}' in '/etc/hosts'.
  lineinfile:
    path: "/etc/hosts"
    line: "{{ application_host }} {{ artifacts_hostname }}"
    state: present
  # Don't run this task on Docker because /etc/hosts is read-only within the container.
  # Instead, we're adding our mapping in the docker run command using the "--add-host" flag. See test.sh.
  when: ansible_hostname != 'nexus-test'

- name: Install unzip program, for extracting Groovy package.
  package: "name=unzip state=latest"

- name: Download and extract Groovy package.
  unarchive:
    src: https://dl.bintray.com/groovy/maven/apache-groovy-binary-{{ groovy_version }}.zip
    dest: "{{ groovy_install_dir }}"
    creates: "{{ groovy_home }}"
    remote_src: yes

- name: "Delete existing local backup of '{{ testing_dir }}', if it exists."
  file: "path={{ testing_dir }}-old state=absent"

- name: "Move '{{ testing_dir }}' to '{{ testing_dir }}-old'."
  shell: "mv {{ testing_dir }} {{ testing_dir }}-old"
  args:
    removes: "{{ testing_dir }}"

- name: "Recreate testing directory."
  file: "path={{ testing_dir }} state=directory"
