---
- name: Assert that timezone has been changed to MDT.
  command: date
  register: date
  # Mountain Time (MT) is Mountain Standard Time (MST, UTC−7:00) when observing standard time,
  # and Mountain Daylight Time (MDT, UTC−6:00) when observing daylight saving time.
  failed_when: "'MDT' not in date.stdout and 'MST' not in date.stdout"

- name: Assert that Nexus returns a status 200 and page content has expected title.
  uri:
    url: "{{ artifacts_base_url }}"
    status_code: 200
    return_content: yes
  register: webpage
  failed_when: "'<title>Nexus Repository Manager</title>' not in webpage.content"

- name: Assert that Nexus process was started by user '{{ nexus_os_user }}'.
  shell: "ps aux | grep org.sonatype.nexus.karaf.NexusMain$"
  register: nexus_proc_info
  # startswith(s) is a function from the Python standard library
  failed_when: not nexus_proc_info.stdout.startswith(nexus_os_user)

- name: Assert that admin password was successfully changed to what we want.
  uri:
    url: "{{ rest_api_endpoint }}"
    user: 'admin'
    password: "{{ nexus_admin_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200   # If the password hasn't been changed, we'll get a 404, which'll cause this task to fail.
