---
- name: Initialize test environment.
  include: tasks/init-test-env.yml
  tags: [ always ]

- name: Test that Nexus was installed and is running as we expect.
  include: tasks/test-install.yml
  tags: [ test-install ]

- name: Test Git LFS repo.
  include: test-gitlfs-repo.yml
  tags: [ test-gitlfs-repo ]

- name: Test raw repo.
  include: test-raw-repo.yml
  tags: [ test-raw-repo ]

- name: Test Maven repos.
  include: test-maven-repos.yml
  tags: [ test-maven-repos ]
