---
groovy_version: 2.4.12
groovy_install_dir: /opt
groovy_home: "{{ groovy_install_dir }}/groovy-{{ groovy_version }}"
groovy_exe: "{{ groovy_home }}/bin/groovy"

testing_dir: /tmp/nexus-IaC-testing

local_remote_repo: "{{ testing_dir }}/repo.git"
test_lfs_push_dir: "{{ testing_dir }}/test-lfs-push"
test_lfs_pull_dir: "{{ testing_dir }}/test-lfs-pull"

# The public base URL of the Nexus server. It is available to all clients. It should NOT include a trailing slash.
artifacts_base_url: "https://{{ artifacts_hostname }}"

lfs_url_without_creds: "{{ artifacts_base_url }}/repository/{{ nexus_repos_gitlfs_hosted[0].name }}/info/lfs"
http_creds_prefix: "https://{{ nexus_local_users[0].username }}:{{ nexus_local_users[0].password }}@"
lfs_url: "{{ lfs_url_without_creds | replace('https://', http_creds_prefix) }}"

# The URL of the 'thredds_doc' repo.
thredds_doc_repo_url: "{{ artifacts_base_url }}/repository/{{ nexus_repos_raw_hosted[0].name }}"

# Pull from 'unidata-all', which is a group repository that includes all other repositories.
maven_pull_repo_url: "{{ artifacts_base_url }}/repository/{{ nexus_repos_maven_group[0].name }}"

# The Maven repository we're pushing to in "test-maven-repos.yml". The test could be run more than once, and the
# deployment needs to work each time. To that end, we're going to push a "1.0.0-SNAPSHOT" version of our library
# to our snapshots repo. That way, a unique version will be generated each time ("1.0.0-" plus a timestamp), and we
# won't have to worry about collisions with existing artifacts in the repo that have the same Maven coordinates.
maven_push_repo_url: "{{ artifacts_base_url }}/repository/{{ nexus_repos_maven_hosted[1].name }}"

# The TaskType ID of the Nexus scheduled task that we will use to test the 'tasks.groovy' script in test_nexus_tasks.yml
# See org.sonatype.nexus.internal.security.apikey.PurgeApiKeysTaskDescriptor
nexus_test_task_type_id: security.purge-api-keys
