---
# Using best practice for maintaining list of sudoers. See https://stackoverflow.com/a/33362805/3874643.

- name: Create 'wheel' group.
  group: name=wheel state=present

- name: Allow 'wheel' group to have passwordless sudo.
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

# See https://unix.stackexchange.com/a/307547
- name: Allow 'nexus_os_user' to start, stop, and restart the Nexus service only.
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ nexus_os_user }}.*\b{{ item }}\b'
    line: '%{{ nexus_os_user }} ALL= NOPASSWD: /bin/systemctl {{ item }} nexus.service'
    validate: visudo -cf %s
  with_items: [ start, stop, restart ]

- name: Create users.
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
  with_items: "{{ users }}"

- name: Set authorized keys for users.
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.ssh_key) }}"
  with_items: "{{ users }}"
