---
- name: Master playbook. Provision Nexus and all supporting services.
  hosts: nexus
  gather_facts: true  # Needed for all the "ansible_*" facts that we use.
  become: true        # Need this for installing packages and starting Nexus service.

  tasks:
    - name: Include 'init' role.
      include_role: name=init
      tags: [ always ]

    # Upgrades ALL system software, rebooting afterwards if necessary. We're not running this on Docker because
    # a) it's slow, and b) you cannot reboot the host from within a container.
    # FIXME: This will lead to differences between the test environment and production. Could be a problem.
    - name: Include 'ansible-debian-upgrade-reboot' role.
      include_role: name=ansible-debian-upgrade-reboot
      tags: [ upgrade ]
      when: ansible_hostname != 'nexus-test'

    - name: Include 'volume' role.
      include_role: name=volume
      tags: [ volume ]
      when: ansible_hostname == 'nexus-prod'  # OpenStack is the only target where we're mounting a volume.

    - name: Include 'security' role.
      include_role: name=security
      tags: [ security ]

    - name: Include 'ansible-role-ntp' role.
      include_role: name=ansible-role-ntp
      tags: [ ntp ]

    - name: Ensure Apache log directories exist for the two domains.
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        # Defined in /ansible/group_vars/all/ansible-role-apache.yml
        - "{{ apache_log_dir }}"
        - "{{ artifacts_apache_log_dir }}"
        - "{{ thredds_doc_apache_log_dir }}"
      tags: [ apache ]

    - name: Include 'ansible-role-apache' role.
      include_role: name=ansible-role-apache
      tags: [ apache ]

    - name: Include 'ansible-oracle-java' role.
      include_role: name=ansible-oracle-java
      tags: [ java ]

    - name: Include 'ansible-nexus3-oss' role.
      include_role: name=ansible-nexus3-oss
      tags: [ nexus ]
