---
- name: Master playbook. Provision Nexus and all supporting services.
  hosts: nexus
  gather_facts: true  # Needed for all the "ansible_*" facts that we use.
  become: true        # Need this for installing packages and starting Nexus service.

  tasks:
    - name: Include 'init' role.
      import_role: name=init
      tags: [ always ]

    - name: Include 'ansible-debian-upgrade-reboot' role.
      import_role: name=ansible-debian-upgrade-reboot
      tags: [ upgrade ]
      # Here we used to have "when: host_type != 'test'", because this role could reboot the host and
      # rebooting from within a Docker container is not supported. That was not ideal because it could lead to
      # differences between test and production. However, I think this role is actually safe to run on 'test'
      # because our test image derives from "ubuntu:16.04", which is frequently and automatically updated.
      # Therefore, the chance that Apt grabs an upgrade that requires a restart (such as a new kernel), AND that the
      # upgrade isn't already part of the latest Docker image, seems quite low. I guess we'll see.

    - name: Include 'volume' role.
      import_role: name=volume
      tags: [ volume ]
      # This role relies on a variable that is only defined in the 'prod' inventory (data_partition_mount_dir).
      when: host_type == 'prod'

    - name: Include 'security' role.
      import_role: name=security
      tags: [ security ]

    - name: Include 'ansible-role-ntp' role.
      import_role: name=ansible-role-ntp
      tags: [ ntp ]

    - name: Ensure Apache log directory exists.
      file:
        # Defined in /ansible/group_vars/all/ansible-role-apache.yml
        path: "{{ artifacts_apache_log_dir }}"
        state: "directory"
      tags: [ apache ]

    - name: Include 'ansible-role-apache' role.
      import_role: name=ansible-role-apache
      tags: [ apache ]

    - name: Include 'oracle-java' role.
      import_role: name=oracle-java
      tags: [ java ]

    - name: Include 'ansible-nexus3-oss' role.
      import_role: name=ansible-nexus3-oss
      tags: [ nexus ]
