---
- name: Prepare Terraform to provision resources on OpenStack.
  hosts: localhost
  gather_facts: false

  vars:
    releases_url: https://releases.hashicorp.com/index.json
    releases_dest: /tmp/index.json
    install_dir: /usr/local/bin

  tasks:
    - name: Install 'jq' for parsing JSON and 'unzip' for extracting Terraform archive.
      package: "name={{ item }} state=latest"
      become: true
      with_items: [ 'jq', 'unzip' ]

    - name: Download Terraform releases index.
      get_url:
        url: "{{ releases_url }}"
        dest: "{{ releases_dest }}"

    - name: Extract latest Terraform release URL from index.
      shell: >
          cat {{ releases_dest }} | jq '{terraform}' | egrep 'linux.*amd64' |
          sort --version-sort -r | head -1 | awk -F[\"] '{print $4}'
      register: latest_terraform_url

    - name: Download and unpack Terraform.
      unarchive:
        src: "{{ latest_terraform_url.stdout }}"
        dest: "{{ install_dir }}"
        creates: "{{ install_dir }}/terraform"
        remote_src: yes
      become: true

    - name: Ensure home directories for OpenStack and AWS exist.
      file: path={{ item }} state=directory
      with_items: [ '~/.openstack', '~/.aws' ]

    - name: Decrypt OpenStack credentials script and copy it to home directory.
      copy:
        src: openrc.sh.enc
        dest: ~/.openstack/openrc.sh
        mode: 0400

    - name: Decrypt AWS credentials file and copy it to home directory.
      copy:
        src: aws_credentials.enc
        dest: ~/.aws/credentials
        mode: 0400
