---
# Some Ansible features depend on Python packages that aren't installed with the default Python distribution.
# We must install those packages ourselves, and of course we use Ansible for the task. Unfortunately, the Ansible
# instance that INSTALLS the packages cannot then USE the packages; they can only be loaded by a brand new Python
# interpreter running a new Ansible instance. As a result, we've separated the Python package installation into its
# own playbook (this file). This playbook should be run before other playbooks that require the packages.
- name: Prepare Ansible to run main playbook on OpenStack target.
  hosts: all
  gather_facts: false

  tasks:
    - name: Install pip Python package manager, updating the cache first, if needed.
      apt:
        name: python-pip
        state: latest
        update_cache: yes
        cache_valid_time: 3600  # Update cache if it's been over an hour since the last update.
      become: true

    # FIXME: Do we actually need to install any of this? Probably 'jmespath', but that could be it.
    # boto and awscli can be installed in backup.yml and resore.yml, I think.
    - name: Install Python packages.
      pip: "name={{ item }} state=latest"
      with_items:
        - jmespath  # Required by the json_query Jinja2 filter. Used in test.yml playbook.
        - boto      # Required by 's3_bucket' module. Used in backup.yml playbook.
        - awscli    # Installs AWS CLI. Used in backup.yml and restore.yml playbooks.

    - name: Ensure home directory for SSH exists.
      file: path=~/.ssh state=directory

    - name: Decrypt OpenStack SSH private key and copy it to home directory.
      copy:
        src: unidata_provisioner_id_rsa.enc
        dest: ~/.ssh/unidata_provisioner_id_rsa
        mode: 0400
      # When this playbook is run on Docker as part of our test suite, it does NOT interact with OpenStack at all.
      # So, don't needlessly decrypt the SSH key.
      when: target_type != 'docker'

  # TODO: Could these tasks--and the stuff in provisioning/files--be moved to a 'prepare' role?
