---
- name: Prepare Terraform to provision resources on OpenStack.
  hosts: localhost

  vars:
    releases_url: https://releases.hashicorp.com/index.json
    releases_dest: /tmp/index.json
    install_dir: /usr/local/bin

  tasks:
    - name: Install 'jq' for parsing JSON and 'unzip' for extracting Terraform archive.
      package: "name={{ item }} state=latest"
      become: true
      with_items: [ 'jq', 'unzip' ]

    - name: Download Terraform releases index.
      get_url:
        url: "{{ releases_url }}"
        dest: "{{ releases_dest }}"

    - name: Extract latest Terraform release URL from index.
      shell: >
          cat {{ releases_dest }} | jq '{terraform}' | egrep 'linux.*amd64' |
          sort --version-sort -r | head -1 | awk -F[\"] '{print $4}'
      register: latest_terraform_url

    - name: Download and unpack Terraform.
      unarchive:
        src: "{{ latest_terraform_url.stdout }}"
        dest: "{{ install_dir }}"
        creates: "{{ install_dir }}/terraform"
        remote_src: yes
      become: true  # User may need elevated privileges to write to 'install_dir'.

    - name: Ensure home directories for SSH, OpenStack, and AWS exist.
      file: path={{ item }} state=directory
      with_items: [ '~/.ssh', '~/.openstack', '~/.aws' ]

    - name: Decrypt credentials files and place them in their respective home directories.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0400
      with_items:
        - { src: unidata_provisioner_id_rsa.enc, dest: ~/.ssh/unidata_provisioner_id_rsa }
        - { src: openrc.sh.enc,                  dest: ~/.openstack/openrc.sh }
        - { src: aws_credentials.enc,            dest: ~/.aws/credentials }
