---
- name: Master playbook. Provision Nexus and all supporting services.
  hosts: all
  gather_facts: yes  # Needed for all the "ansible_*" facts that we use.
  become: yes        # Need this for starting nexus service.

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include: tasks/init.yml
      tags: [ 'init' ]

  roles:
    - { role: ansible-role-ntp,   tags: [ 'ntp'   ] }
    - { role: oracle-java,        tags: [ 'java'  ] }
    - { role: ansible-nexus3-oss, tags: [ 'nexus' ] }
