---
- name: Master playbook. Provision Nexus and all supporting services.
  hosts: all
  gather_facts: yes  # Needed by 'oracle-java' role for 'ansible_os_family'. Probably many other places too.
  become: yes        # Need this for starting nexus service.

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include: tasks/init.yml

  roles:
    - { role: ansible-role-ntp,   tags: [ 'ntp'   ] }
    - { role: oracle-java,        tags: [ 'java'  ] }
    - { role: ansible-nexus3-oss, tags: [ 'nexus' ] }

  tasks:
    - include: tasks/tests.yml
      tags: ['test']
