---
- name: Master playbook. Provision Nexus and all supporting services.
  hosts: all
  gather_facts: yes  # Needed by 'oracle-java' role for 'ansible_os_family'. Probably many other places too.
  become: yes        # Need this for starting nexus service.

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include: tasks/init.yml

  roles:
    - ansible-role-ntp
    - oracle-java
    # While we're using end_play in ansible-nexus3-oss's main.yml, we'll need to comment this out if we want to test.
    - ansible-nexus3-oss

  tasks:
    - include: tasks/tests.yml
      tags: ['test']
      # And we'll also have to define these, because they're not set in 'ansible-nexus3-oss' any more.
      vars:
        nexus_default_port: 8081
        nexus_os_user: 'nexus'
