---
  # Note: This is the only playbook where we don't need to decrypt something in Ansible Vault. Yet.
- name: Test playbook. Execute integration and functional tests against running Nexus server.
  hosts: nexus
  gather_facts: true  # Needed for all the "ansible_*" facts that we use.
  become: true        # For installing software needed by tests.

  tasks:
    - name: Include 'github-git-lfs' role.
      include_role: name=github-git-lfs
      tags: [ git-lfs ]

    - name: Include 'testing' role.
      include_role: name=testing
      tags: [ test ]
