---
- name: Test playbook. Execute integration and functional tests against running Nexus server.
  hosts: all
  gather_facts: yes  # Needed for all the "ansible_*" facts that we use.
  become: yes        # For installing software needed by tests.

  roles:
    - role: github-git-lfs
      tags: [ git-lfs ]
    - role: testing
      tags: [ test ]
