resource "openstack_blockstorage_volume_v2" "nexus" {
  name        = "nexus-volume"
  description = "Stores all application data generated by Nexus repository manager"
  size        = "${var.volume_size}"  // In GB.
}

resource "openstack_compute_volume_attach_v2" "nexus" {
  instance_id = "${openstack_compute_instance_v2.nexus.id}"
  volume_id   = "${openstack_blockstorage_volume_v2.nexus.id}"
}
