---
ansible_user: ubuntu
#ansible_user: debian
ansible_ssh_private_key_file: ~/.ssh/unidata_provisioner_id_rsa

# The directory to which the Cinder volume's partition will be mounted.
data_partition_mount_dir: /data

# These definitions override the ones in group_vars/all/ansible-nexus3-oss.yml. We're exploiting the fact that
# inventory variables defined in a "group_vars/*" file (such as this one) have higher precedence than playbook
# variables defined in "group_vars/all".
# See http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
nexus_data_dir: "{{ data_partition_mount_dir }}/nexus"
nexus_backup_dir: "{{ data_partition_mount_dir }}/nexus-backup"

# Overrides definition in group_vars/all/ansible-role-apache.yml.
# On OpenStack, we want for all data that will be backed up to live on the Cinder volume.
apache_log_dir: "{{ data_partition_mount_dir }}/apache2-log"
